method: onet

data:
  dataset: iGibson
  input_type: pointcloud
  path: data/igibson_obj
  pointcloud_n: 300
  pointcloud_noise: 0.005
  points_subsample: 2048 
  voxels_file: null
model:
  encoder_latent: null
  decoder: cbatchnorm
  encoder: pointnet_resnet
  encoder_kwargs:
    hidden_dim: 512 
  c_dim: 512 
  z_dim: 0
training:
  out_dir:  igibson_out/pointcloud/onet
  batch_size: 256
  model_selection_metric: iou
  model_selection_mode: maximize
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: /mnt/cap/fangchuan/DeepPanoContext/ONet/igibson_out/pointcloud/onet/model_20221012.pt
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1

